live_config_reload = true

[env]
TERM = "alacritty"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"
bright_foreground = "#ffffff"
dim_foreground = "#9a9a9a"
foreground = "#eaeaea"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[scrolling]
history = 20000

[window.dimensions]
columns = 120
lines = 28

